# Generated by Django 4.2.7 on 2024-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
